name: "Compile and Test"
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ghdl/ghdl:5.1.1-llvm-jit-ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y make

      - name: Compile and test VHDL files
        run: make test -j
